AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AI Interview FastAPI Application

Globals:
  Function:
    Timeout: 120
    MemorySize: 512
    Runtime: python3.9
    Tags:
      test-ai-interview-bootcamp: true
      creator: anuj-jadhav

Resources:
  AIInterviewFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./package
      Handler: lambda_handler.handler
      Description: AI Interview FastAPI Application
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          STAGE: prod
          REGION: !Ref AWS::Region
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: '*'

Outputs:
  AIInterviewApi:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/" 